name: pytorch1.3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - appdirs=1.4.3=py_1
  - audioread=2.1.8=py37hc8dfbb8_2
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h8f50634_1000
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.2=py37he30daa8_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1=py37hb09aad4_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask-core=2.25.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he6710b0_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.10.2=h5ab3b9f_0
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.65.0=h3eb4bd4_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - graphite2=1.3.13=he1b5a44_1001
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - jasper=2.0.14=h07fcdf6_1
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=he1b5a44_0
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - libllvm10=10.0.1=he513fc3_3
  - libogg=1.3.2=h516909a_1002
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - librosa=0.8.0=pyh9f0ad1d_0
  - libsndfile=1.0.29=he1b5a44_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.7=he1b5a44_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - llvmlite=0.34.0=py37h5202443_1
  - lz4-c=1.9.2=he6710b0_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.5=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - numba=0.51.2=py37h9fdb41a_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1g=h516909a_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.1=py37he6710b0_0
  - pcre=8.44=he6710b0_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - pixman=0.38.0=h516909a_1003
  - pooch=1.2.0=py_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pysoundfile=0.10.2=py_1001
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - resampy=0.2.2=py_0
  - scikit-image=0.16.2=py37h0573a6f_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=49.6.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.49.0=pyh9f0ad1d_0
  - urllib3=1.25.10=py_0
  - wheel=0.35.1=py_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/linhui.dai/anaconda2/envs/pytorch1.3

